# Generated by Django 2.2.5 on 2019-10-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Racket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_seller', models.TextField()),
                ('address', models.TextField()),
                ('name_bat', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
                ('desc', models.TextField(max_length=200)),
                ('model_no', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date_make', models.DateField()),
            ],
        ),
    ]
