# Generated by Django 2.2.5 on 2019-10-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racket',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
