# Generated by Django 2.2.5 on 2019-10-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_racket_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='racket',
            name='email',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
