# Generated by Django 2.2.5 on 2019-10-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20191009_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racket',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
